version: "3.6"

services:

  minetest:
    image: registry.gitlab.com/minetest/minetest/server:latest
    container_name: minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/minetest-data/:/var/lib/minetest/
      - /srv/minetest-client/conf/:/etc/minetest/
    ports:
      - 30000:30000/udp
    #command: ["sleep", "82000"] #"/usr/local/bin/minetestserver", "--config", "/etc/minetest/minetest.conf", "--trace"]
    restart: unless-stopped

