services:
        minetest:
                image: registry.gitlab.com/minetest/minetest/server:latest
                container_name: minetest
                environment:
                        - PUID=1000
                        - PGID=1000
                        - TZ=Europe/London
                volumes:
                        - /home/noisebridge/data/minetest:/config/.minetest
                ports:
                        - 30000:30000/udp
                restart: unless-stopped

